from .adapter import TorchClassificationAdapter
from .multitask_adapter import TorchMultiTaskClassificationAdapter
from .contrastive import (
    AmplitudeScaling,
    ChannelMasking,
    ContrastiveFoldData,
    ContrastiveForwardResult,
    ContrastiveLossResult,
    ContrastiveModule,
    ContrastiveObjective,
    ContrastiveTrainingBatch,
    EEGAugmentationPipeline,
    GaussianNoise,
    ProjectionHead,
    TemporalShift,
    TimeMasking,
    aggregate_contrastive_loss_results,
    encoder_architecture_signature,
    export_encoder_checkpoint,
    load_encoder_checkpoint,
    nt_xent_logits,
)
from .dann import (
    DANN_CHECKPOINT_SCHEMA_VERSION,
    DANNFoldData,
    DANNForwardResult,
    DANNLossResult,
    DANNModule,
    DANNObjective,
    DANNPartition,
    DANNTrainingBatch,
    DomainDiscriminator,
    GradientReversal,
    aggregate_dann_loss_results,
)
from .eegnet import TorchEEGNetClassifier, build_torch_eegnet
from .encoder import (
    ENCODER_API_VERSION,
    EncoderModelProtocol,
    SharedEncoderMixin,
    require_encoder_model,
)
from .lstm import TorchLSTMClassifier, build_torch_lstm
from .mlp import TorchMLP, build_torch_mlp
from .ordinal import (
    CategoricalCornObjectiveHandler,
    CategoricalCornOutput,
    ClassificationObjectiveHandler,
    CompositeLoss,
    CoralOrdinalHead,
    CornOrdinalHead,
    build_corn_targets_and_masks,
    build_cumulative_targets,
    coral_loss,
    corn_loss,
    cumulative_to_class_probabilities,
    decode_ordinal_prediction,
    expected_rank,
    threshold_logits_to_cumulative_probabilities,
)
from .shallow_convnet import (
    SafeLog,
    SquareActivation,
    TorchShallowConvNetClassifier,
    build_torch_shallow_convnet,
)
from .shallow_multitask import (
    TorchShallowConvNetMultiTaskClassifier,
    build_torch_shallow_convnet_multitask,
)
from .shallow_fusion import (
    TorchShallowFusionClassifier,
    build_torch_shallow_fusion,
)
from .transformer import (
    TorchFeatureTransformerClassifier,
    TransformerPositionalEncoding,
    build_torch_transformer,
)

__all__ = [
    "TorchClassificationAdapter",
    "TorchMultiTaskClassificationAdapter",
    "AmplitudeScaling",
    "ChannelMasking",
    "ContrastiveFoldData",
    "ContrastiveForwardResult",
    "ContrastiveLossResult",
    "ContrastiveModule",
    "ContrastiveObjective",
    "ContrastiveTrainingBatch",
    "EEGAugmentationPipeline",
    "GaussianNoise",
    "ProjectionHead",
    "TemporalShift",
    "TimeMasking",
    "aggregate_contrastive_loss_results",
    "encoder_architecture_signature",
    "export_encoder_checkpoint",
    "load_encoder_checkpoint",
    "nt_xent_logits",
    "DANN_CHECKPOINT_SCHEMA_VERSION",
    "DANNFoldData",
    "DANNForwardResult",
    "DANNLossResult",
    "DANNModule",
    "DANNObjective",
    "DANNPartition",
    "DANNTrainingBatch",
    "DomainDiscriminator",
    "GradientReversal",
    "aggregate_dann_loss_results",
    "TorchEEGNetClassifier",
    "ENCODER_API_VERSION",
    "EncoderModelProtocol",
    "SharedEncoderMixin",
    "require_encoder_model",
    "TorchLSTMClassifier",
    "TorchMLP",
    "CategoricalCornObjectiveHandler",
    "CategoricalCornOutput",
    "ClassificationObjectiveHandler",
    "CompositeLoss",
    "CoralOrdinalHead",
    "CornOrdinalHead",
    "TorchShallowConvNetClassifier",
    "TorchShallowConvNetMultiTaskClassifier",
    "TorchShallowFusionClassifier",
    "TorchFeatureTransformerClassifier",
    "TransformerPositionalEncoding",
    "SquareActivation",
    "SafeLog",
    "build_torch_lstm",
    "build_torch_eegnet",
    "build_torch_mlp",
    "build_torch_shallow_convnet",
    "build_torch_shallow_convnet_multitask",
    "build_torch_shallow_fusion",
    "build_torch_transformer",
    "build_corn_targets_and_masks",
    "build_cumulative_targets",
    "coral_loss",
    "corn_loss",
    "cumulative_to_class_probabilities",
    "decode_ordinal_prediction",
    "expected_rank",
    "threshold_logits_to_cumulative_probabilities",
]
